#!/bin/bash
wtr=$(echo "$WATER" | tr "ewatrsd" "0123456"); str=$(echo "$STIR" | tr "ti.r" "0123"); echo "7i 4o $wtr $str + p" | dc | tr "01234567" "bchloes"
W=$(echo "$WATER" | tr "ewatrsd" "0123456"); S=$(echo "$STIR" | tr "ti.r" "0123"); echo "7i 4o $W $S + p" | dc | tr "0123456" "bchloes"
